apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jmo93zn33-nodejs
  janus-idp.io/tekton: jmo93zn33-nodejs
  backstage.io/kubernetes-id: jmo93zn33-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jmo93zn33-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
