apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jmo93zn33-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jmo93zn33-nodejs 
  name: jmo93zn33-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jmo93zn33-nodejs 
